<a href="https://colab.research.google.com/github/albertomendess/algoritmos-e-python/blob/main/PYTHON_PARA_PROGRAMA%C3%87%C3%83O_DE_ALGOR%C3%8DTMOS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
import numpy as np

# CRIANDO E USANDO STRINGS

In [1]:
ord("A")

65

In [2]:
ord("a")

97

In [3]:
a = ord("a")

In [4]:
a

97

In [5]:
myInt = int("123")

In [6]:
myInt

123

In [7]:
myStr = str(1234.56)
myStr

'1234.56'

In [8]:
a = 1
b = "1"

## OPERADORES DE ASSOCIAÇÃO DE PYTHON

In [9]:
a = "Hello Everyone"
b = "Hello"

In [10]:
b in a

True

In [11]:
b not in a

False

## OPERADORES DE IDENTIDADE DE PYTHON

In [12]:
a is b

False

In [13]:
a is not b

True

# INTERAGINDO COM DATAS

In [14]:
import datetime

In [15]:
datetime.datetime.now()

datetime.datetime(2021, 4, 24, 18, 29, 56, 720916)

In [16]:
str(datetime.datetime.now().date())

'2021-04-24'

In [17]:
str(datetime.datetime.now().time())

'18:29:56.756516'

# CRIANDO E USANDO FUNÇÕES

In [18]:
def SayHello():
    print("Hello There!")

In [19]:
SayHello()

Hello There!


In [20]:
SayHello

<function __main__.SayHello>

##CHAMANDO FUNÇÕES

##ARGUMENTOS DE REQUISIÇÃO DE ENVIO

In [21]:
def DoSum(Value1, Value2):
    return Value1 + Value2

In [22]:
DoSum(1, 2)

3

###ENVIANDO ARGUMENTOS POR PALAVRA-CHAVE

In [23]:
def DisplaySum(Value1, Value2):
    print(str(Value1) + ' + ' + str(Value2) + ' = ' +
    str((Value1 + Value2)))

In [24]:
DisplaySum(2, 3)

2 + 3 = 5


In [25]:
DisplaySum(Value2=3, Value1=2)

2 + 3 = 5


###DANDO UM VALOR PADRÃO A ARGUMENTOS DE FUNÇÃO

In [26]:
def SayHello(Greeting = "No Value Supplied"):
    print(Greeting)

In [27]:
SayHello()

No Value Supplied


In [28]:
SayHello("Howdy!")

Howdy!


###CRIANDO FUNÇÕES COM UM NÚMERO VARIÁVEL DE ARGUMENTOS

In [29]:
def DisplayMulti(ArgCount = 0, *VarArgs):
    print("You passed " + str(ArgCount) + " arguments.", VarArgs)

In [30]:
DisplayMulti()

You passed 0 arguments. ()


In [31]:
DisplayMulti(3, 'a', 'b', 'c')

You passed 3 arguments. ('a', 'b', 'c')


#USANDO EXPRESSÕES CONDICIONAIS E DE LOOP

###TOMANDO DECISÕES USANDO A EXPRESSÃO 'if'

In [32]:
def TestValue(Value):
    if Value <= 5:
        print("Value less than or equal to 5")
    elif Value <= 10:
        print("Value less than or equal to 10")
    else:
        print("Value greater than 10.")

In [33]:
TestValue(10)

Value less than or equal to 10


###ESCOLHENDO ENTRE VÁRIAS OPÇÕES USANDO DECISÕES ANINHADAS

In [34]:
def SecretNumber():
    One = int(input("Type a number between 1 and 10: "))
    Two = int(input("Type a number between 1 and 10: "))

    if (One >= 1) and (One <= 10):
        if (Two >= 1) and (Two <= 10):
            print("Your secret number is: " + str(One * Two))
        else:
            print("Incorret second value!")
    else:
        print("Incorret second value!")

In [36]:
SecretNumber()

Type a number between 1 and 10: 1
Type a number between 1 and 10: 1
Your secret number is: 1


###EXECUTANDO TAREFAS REPETITIVAS USANDO O CICLO REPETITIVO 'for'

In [ ]:
def DisplayMulti(*VarArgs):
    for Arg in VarArgs:
        if Arg.upper() == 'CONT':
            continue
            print("Continue Argument: " + Arg)
        elif Arg.upper() == 'BREAK':
            break
            print("Break Argument: " + Arg)
        print("Good argument: " + Arg)

In [ ]:
DisplayMulti('Hello', 'Goodbye', 'Python', 'Last')

In [ ]:
DisplayMulti('Hello', 'cont', 'python', 'break', 'invisible')

###USANDO A INSTRUÇÃO 'while'

In [ ]:
def SecretNumber():
    GotIt = False
    while GotIt == False:
        One = int(input("Type a number between 1 and 10: "))
        Two = int(input("Type a number between 1 and 10: "))

        if (One >= 1) and (One <= 10):
            if (Two >= 1) and (Two <= 10):
                print("Secret number is: " + str(One * Two))
                GotIt = True
                continue
            else:
                print("Incorrect second value!")
        else:
            print("Incorrect first value!")
        print("Try again!")

In [ ]:
SecretNumber()

#ARMAZENANDO DADOS EM CONJUNTOS, LISTAS E TUPLAS

###CRIANDO CONJUNTOS

In [ ]:
setA = set(['red', 'Blue', 'Green', 'Black'])
setB = set(['Black', 'Green', 'Yellow', 'Orange'])
setX = setA.union(setB)
setY = setA.intersection(setB)
setZ = setA.difference(setB)

In [ ]:
print('{0}\n{1}\n{2}'.format(setX, setY, setZ))

In [ ]:
setA.issubset(setX)

In [ ]:
setA.issuperset(setY)

In [ ]:
setA.add('Purple')
setA

In [ ]:
setA.issubset(setX)

###CRIANDO LISTAS

In [ ]:
listA = [0, 1, 2, 3]
listB = [4, 5, 6, 7]

In [ ]:
listA.extend(listB)

In [ ]:
listA

In [ ]:
listA.append(-5)

In [ ]:
listA

In [ ]:
listA.remove(-5)

In [ ]:
listA

In [ ]:
listX = [10, 20, 30, 40]
listY = [50, 60, 70, 80]

In [ ]:
listZ = listX + listY

In [ ]:
listZ

In [ ]:
listX

In [ ]:
listY

###CRIANDO E USANDO TUPLAS

In [ ]:
myTuple = (1, 2, 3, (4, 5, 6, (7, 8, 9)))

In [ ]:
for value1 in myTuple:
    if type(value1) == int:
        print(value1)
    else:
        for value2 in value1:
            if type(value2) == int:
                print("\t", value2)
            else:
                for value3 in value2:
                    print("\t\t", value3)

In [ ]:
myNewTuple = myTuple.__add__((10, 11, 12, (13, 14, 15)))
myNewTuple

#DEFININDO ITERADORES ÚTEIS

In [ ]:
listA = ['Orange', 'Yellow', 'Green', 'Brown', 'Red']
listB = [1, 2, 3, 4, 5]

In [ ]:
listA[1]

In [ ]:
for value in listB[1:3]:
    print(value)

In [ ]:
listA[:3]

In [ ]:
for value1, value2 in zip(listA, listB):
    print(value1, '\t', value2)

#INDEXANDO DADOS USANDO DICIONÁRIOS

In [ ]:
myDict = {'Orange': 1, 'Blue': 2, 'Pink':3}

In [ ]:
myDict

In [ ]:
myDict['Pink']

In [ ]:
myDict.keys()

In [ ]:
myDict.values()

In [ ]:
myDict.items()

In [ ]:
for key, value in myDict.items():
    print(key, "\t", value)

## Definindo operações matriciais avançadas

In [39]:
changeIt = np.array([1, 2, 3, 4, 5, 6, 7, 8])

changeIt

array([1, 2, 3, 4, 5, 6, 7, 8])

In [40]:
changeIt.reshape(2, 4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [42]:
changeIt.reshape(2, 2, 2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [46]:
changeIt = changeIt.reshape(2, 4)
changeIt

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [47]:
np.transpose(changeIt)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [54]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [55]:
a = np.array([[1, 2], [3, 4]])
b = np.linalg.inv(a)

In [56]:
np.allclose(np.dot(a, b), np.identity(2))

True

## Criando combinações do jeito certo
### Distinguindo permutações